import { ProductItem, SubServiceItem } from "@/types";

// ==========================================
// 1. EVDE SAĞLIK HİZMETLERİ (SUB-SERVICES)
// ==========================================
export const EVDE_SAGLIK_SERVICES: SubServiceItem[] = [
  {
    id: "sag-evde-muayene",
    categoryId: "evde-saglik",
    name: "Evde Genel Fiziki Muayene",
    description: "Evcil dostunuzun kendi ev ortamında, kliniğe gitme stresi yaşamadan uzman veteriner hekim tarafından tepeden tırnağa fiziki muayenesi.",
    price: 850,
    unit: "Seans (45 dk)",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&auto=format&fit=crop&q=80",
    features: ["Stresiz ortam muayenesi", "Kalp, Akciğer ve Nabız Kontrolü", "Göz, Kulak ve Ağız İncelemesi", "Karne ve Aşı Takvimi Planlaması"],
  },
  {
    id: "sag-kedi-karma-asi",
    categoryId: "evde-saglik",
    name: "Evde Yıllık Kedi Karma Aşısı",
    description: "Kedileri Feline Panleukopenia, Calicivirus ve Rhinotracheitis virüslerine karşı koruyan yıllık koruyucu soğuk zincir aşısı.",
    price: 750,
    unit: "1 Doz",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    features: ["Soğuk Zincir Güvencesi", "3 Virüse Karşı Tam Koruma", "Resmi Sağlık Karnesi İşleme"],
  },
  {
    id: "sag-kopek-karma-asi",
    categoryId: "evde-saglik",
    name: "Evde Yıllık Köpek Karma Aşısı",
    description: "Köpeklerde Gençlik Hastalığı (Distemper), Parvovirus, Hepatit ve Leptospirosis virüslerine karşı yıllık temel karma aşı.",
    price: 800,
    unit: "1 Doz",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80",
    features: ["Soğuk Zincir Garantisi", "5'li Geniş Virüs Spektrumu", "Karne ve Çip Onayı"],
  },
  {
    id: "sag-kedi-losemi-asi",
    categoryId: "evde-saglik",
    name: "Evde Yıllık Kedi Lösemi Aşısı (FeLV)",
    description: "Kedi Lösemi Virüsü (FeLV) enfeksiyonuna karşı yıllık koruyucu aşı uygulaması.",
    price: 900,
    unit: "1 Doz",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&auto=format&fit=crop&q=80",
    requiresNotice: true,
    noticeText: "ZORUNLU UYARI: İlk defa lösemi aşısı yaptıracak kedilerde aşı öncesi Hızlı Test Kiti ile FeLV/FIV testi yapılması zorunludur.",
    features: ["FeLV Koruması", "İlk Aşılamada Hızlı Test Şartı", "Hekim Takibi"],
  },
  {
    id: "sag-kopek-bronsin-asi",
    categoryId: "evde-saglik",
    name: "Evde Yıllık Köpek Bronşin Aşısı",
    description: "Köpek Barınak Öksürüğü (Kennel Cough - Bordetella bronchiseptica) hastalığına karşı koruyucu aşı.",
    price: 750,
    unit: "1 Doz",
    image: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&auto=format&fit=crop&q=80",
    features: ["Solunum Yolu Enfeksiyon Koruması", "Sosyal ve Parka Çıkan Köpekler İçin İdeal", "Burun İçi / Enjeksiyon"],
  },
  {
    id: "sag-kuduz-asi",
    categoryId: "evde-saglik",
    name: "Evde Yıllık Kuduz Aşısı (Kedi & Köpek)",
    description: "Yasal olarak zorunlu olan ve tüm kedi & köpek dostlarımıza yıllık uygulanan orijinal bakanlık onaylı kuduz aşısı.",
    price: 500,
    unit: "1 Doz",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format&fit=crop&q=80",
    features: ["Yasal Zorunlu Aşı", "Bakanlık Onaylı Orijinal Aşı", "Resmi Sağlık Karnesi ve PETVET Onayı"],
  },
  {
    id: "sag-kedi-aylik-parazit",
    categoryId: "evde-saglik",
    name: "Evde Kedi Aylık İç/Dış Antiparaziter",
    description: "Kediler için 1 aylık koruma sağlayan orijinal ense damlası ve iç parazit uygulaması.",
    price: 650,
    unit: "Uygulama",
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&auto=format&fit=crop&q=80",
    features: ["1 Ay Tam Koruma", "Pire, Kene ve Bağırsak Parazitleri", "Hekim Tarafından Ense Damlası"],
  },
  {
    id: "sag-kedi-3aylik-parazit",
    categoryId: "evde-saglik",
    name: "Evde Kedi 3 Aylık İç/Dış Antiparaziter",
    description: "3 ay boyunca kesintisiz tam geniş spektrumlu koruma sağlayan premium parazit uygulaması.",
    price: 1250,
    unit: "Uygulama",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&auto=format&fit=crop&q=80",
    features: ["3 Ay Kesintisiz Etki", "Geniş Spektrumlu Güvenlik", "Evde Hızlı Hekim Uygulaması"],
  },
  {
    id: "sag-kopek-dis-parazit",
    categoryId: "evde-saglik",
    name: "Evde Köpek Dış Parazit Uygulaması",
    description: "Köpeğinizin kilo aralığına uygun orijinal dış parazit damla veya lezzetlendirilmiş tablet uygulaması.",
    price: 750,
    unit: "Uygulama",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&auto=format&fit=crop&q=80",
    weightOptions: ["2.5 - 5 kg (550₺)", "5 - 10 kg (650₺)", "10 - 20 kg (750₺)", "20 - 40 kg (850₺)"],
    features: ["Kilo Odaklı Dozajlama", "Pire & Kene Koruması", "Evde Hekim Uygulaması"],
  },
  {
    id: "sag-evde-kan-laboratuvar",
    categoryId: "evde-saglik",
    name: "Evde Kan Alma & Hemogram Biyokimya",
    description: "Steril koşullarda evde kan alımı, soğuk zincirle akredite laboratuvara ulaştırılması ve aynı gün hekim yorumlu raporlama.",
    price: 950,
    unit: "Seans",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80",
    features: ["Steril Kan Alımı", "Hemogram (18 Parametre) + Biyokimya", "Aynı Gün PDF Rapor & Hekim Değerlendirmesi"],
  },
  {
    id: "sag-evde-serum-tedavisi",
    categoryId: "evde-saglik",
    name: "Evde Serum & Sıvı Elektrolit Tedavisi",
    description: "İshal, kusma veya iştahsızlık kaynaklı dehidrasyon durumlarında damar yolu açılarak serum ve vitamin infüzyonu.",
    price: 850,
    unit: "Seans (60 dk)",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&auto=format&fit=crop&q=80",
    features: ["Damar İçi Sıvı Desteği", "B Kompleks & Elektrolit Takviyesi", "Hekim Başında Bekleme"],
  },
  {
    id: "sag-evde-tirnak-pati",
    categoryId: "evde-saglik",
    name: "Evde Tırnak Kesimi & Pati Hijyen Bakımı",
    description: "Damara zarar vermeden emniyetli tırnak kesimi, pati arası tüylerinin düzeltilmesi ve organik pati nemlendirici uygulaması.",
    price: 350,
    unit: "Seans",
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&auto=format&fit=crop&q=80",
    features: ["Emniyetli Tırnak Kesimi", "Pati Altı Tüy Temizliği", "Organik Onarıcı Balm"],
  },
  {
    id: "sag-evde-mikrocip-petvet",
    categoryId: "evde-saglik",
    name: "Evde Mikroçip & PETVET Resmi Kayıt",
    description: "ISO standartlarında 15 haneli mikroçip implantasyonu ve Tarım Bakanlığı PETVET sistemine anlık resmi kayıt.",
    price: 650,
    unit: "Uygulama",
    image: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&auto=format&fit=crop&q=80",
    features: ["ISO 11784/11785 Çip", "Anlık PETVET Kaydı", "Resmi Çip Sertifikası"],
  },
];

// ==========================================
// 2. EVE MAMA ÜRÜNLERİ (FOOD CATALOG)
// ==========================================
export const MAMA_PRODUCTS: ProductItem[] = [
  {
    id: "mama-rc-sterilised",
    name: "Royal Canin Sterilised Kısırlaştırılmış Kedi Maması",
    brand: "Royal Canin",
    category: "eve-mama",
    subCategory: "Kısırlaştırılmış",
    species: "Kedi",
    price: 980,
    originalPrice: 1120,
    rating: 4.9,
    ratingCount: 142,
    unit: "4 kg",
    weightOptions: ["2 kg (580 ₺)", "4 kg (980 ₺)", "10 kg (2.150 ₺)"],
    description: "Kısırlaştırılmış 1-7 yaş arası yetişkin kedilerin kilo kontrolünü sağlayan ve üriner sistem sağlığını koruyan optimum dengeli kuru mama.",
    features: ["Yağ oranını sınırlandırarak ideal kiloyu korur", "Dengeli mineral içeriği ile idrar yolu sağlığını destekler", "Yüksek L.I.P protein sindirilebilirliği"],
    image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Çok Satan", "%12 İndirim"],
  },
  {
    id: "mama-rc-gastro",
    name: "Royal Canin Veterinary Gastrointestinal Kedi/Köpek Maması",
    brand: "Royal Canin Veterinary",
    category: "eve-mama",
    subCategory: "Reçeteli Seri",
    species: "Tümü",
    price: 1350,
    rating: 4.8,
    ratingCount: 96,
    unit: "2 kg",
    weightOptions: ["2 kg (1.350 ₺)", "4 kg (2.450 ₺)"],
    description: "Akut bağırsak emilim bozuklukları, sindirim hassasiyeti ve nekahat dönemindeki kedi/köpekler için yüksek enerjili klinik diyetetik mama.",
    features: ["Yüksek sindirilebilir formül ve dengeli lifler", "Azaltılmış porsiyonla yüksek enerji sağlama", "Prebiyotik MOS ve FOS desteği"],
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    isPrescriptionNeeded: true,
    badges: ["Veteriner Reçeteli"],
  },
  {
    id: "mama-proplan-salmon",
    name: "Pro Plan Adult Original Somonlu Yetişkin Kedi Maması",
    brand: "Pro Plan",
    category: "eve-mama",
    subCategory: "Kuru Mama",
    species: "Kedi",
    price: 890,
    originalPrice: 990,
    rating: 4.9,
    ratingCount: 88,
    unit: "3 kg",
    weightOptions: ["1.5 kg (490 ₺)", "3 kg (890 ₺)", "10 kg (1.950 ₺)"],
    description: "Gerçek somon balığı eti içeren, böbrek sağlığını korumaya yardımcı Optirenal formüllü süper premium yetişkin kedi maması.",
    features: ["Gerçek somon proteini", "Böbrek fonksiyonlarını koruyan Optirenal kompleksi", "İpeksi tüy ve sağlıklı deri yapısı"],
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Popüler"],
  },
  {
    id: "mama-hills-urinary",
    name: "Hill's Prescription Diet c/d Multicare Urinary Care",
    brand: "Hill's",
    category: "eve-mama",
    subCategory: "Reçeteli Seri",
    species: "Kedi",
    price: 1290,
    rating: 4.7,
    ratingCount: 65,
    unit: "1.5 kg",
    description: "İdrar yollarında struvit ve kalsiyum oksalat taşlarının tekrarlamasını önlemek üzere klinik olarak kanıtlanmış veteriner maması.",
    features: ["Struvit taşlarını 7 günde çözmeye yardımcı olur", "İdrar pH seviyesini hedeflenen aralıkta tutar", "L-triptofan ile stres yönetimini destekler"],
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    isPrescriptionNeeded: true,
    badges: ["Klinik Reçeteli"],
  },
  {
    id: "mama-nd-grainfree-kedi",
    name: "N&D Grain Free Balıklı & Balkabaklı Kedi Maması",
    brand: "N&D Farmina",
    category: "eve-mama",
    subCategory: "Tahılsız",
    species: "Kedi",
    price: 1150,
    originalPrice: 1280,
    rating: 5.0,
    ratingCount: 110,
    unit: "5 kg",
    weightOptions: ["1.5 kg (460 ₺)", "5 kg (1.150 ₺)", "10 kg (2.290 ₺)"],
    description: "Tahılsız, %96 hayvansal kaynaklı protein ve taze balkabağı ile formüle edilmiş ultra lüks gurme kedi maması.",
    features: ["%0 Tahıl, %96 Hayvansal Protein", "Düşük glisemik indeks", "Doğal antioksidan ve taze balık"],
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Tahılsız Ultra"],
  },
  {
    id: "mama-proplan-kopek-medium",
    name: "Pro Plan Medium Adult Kuzu Etli Köpek Maması",
    brand: "Pro Plan",
    category: "eve-mama",
    subCategory: "Kuru Mama",
    species: "Köpek",
    price: 1200,
    originalPrice: 1350,
    rating: 4.8,
    ratingCount: 74,
    unit: "3 kg",
    weightOptions: ["3 kg (1.200 ₺)", "14 kg (3.400 ₺)"],
    description: "Hassas sindirime sahip orta ırk yetişkin köpekler için gerçek kuzu eti ve OPTIDIGEST içerikli tam dengeli kuru mama.",
    features: ["Yüksek kaliteli kuzu eti", "Prebiyotik liflerle sağlıklı dışkı kalitesi", "Güçlü kas yapısı için optimum protein"],
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "mama-royalcanin-pouch-kitten",
    name: "Royal Canin Kitten Yaş Mama Pouch (12 x 85 gr)",
    brand: "Royal Canin",
    category: "eve-mama",
    subCategory: "Yaş Mama",
    species: "Kedi",
    price: 480,
    originalPrice: 540,
    rating: 4.9,
    ratingCount: 128,
    unit: "12'li Paket",
    description: "Yavru kedilerin bağışıklık sistemi gelişimini destekleyen, sos içinde lezzetli et parçacıklı konserve mama paketi.",
    features: ["Yavru dişlerine uygun küçük yumuşak parçalar", "Bağışıklık destekleyici vitamin kompleksi", "Yüksek hidrasyon ve lezzet"],
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["12'li Ekonomik Paket"],
  },
  {
    id: "mama-acana-wild-prairie",
    name: "Acana Wild Prairie Dog Tahılsız Köpek Maması",
    brand: "Acana",
    category: "eve-mama",
    subCategory: "Tahılsız",
    species: "Köpek",
    price: 1650,
    rating: 4.9,
    ratingCount: 52,
    unit: "6 kg",
    weightOptions: ["2 kg (680 ₺)", "6 kg (1.650 ₺)", "11.4 kg (2.950 ₺)"],
    description: "Serbest dolaşan tavuk, hindi, bütün yumurta ve vahşi balık içeren biyolojik olarak uygun tahılsız köpek maması.",
    features: ["%70 Kaliteli Hayvansal İçerik", "%30 Taze Meyve, Sebze ve Bitkiler", "Kanada'nın ödüllü mutfaklarında üretim"],
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Premium İthal"],
  },
];

// ==========================================
// 3. EVE PETSHOP ÜRÜNLERİ (PETSHOP CATALOG)
// ==========================================
export const PETSHOP_PRODUCTS: ProductItem[] = [
  {
    id: "shop-bentonit-kedi-kumu",
    name: "Bentonit Doğal Kedi Kumu (İnce Tane, Kokusuz)",
    brand: "EverClean / VanCat",
    category: "eve-petshop",
    subCategory: "Kedi Kumu",
    species: "Kedi",
    price: 240,
    originalPrice: 280,
    rating: 4.9,
    ratingCount: 215,
    unit: "10 Litre",
    description: "%99.5 tozsuz, sıvı temasında anında taş gibi topaklanan %100 doğal beyaz bentonit kedi kumu.",
    features: ["Anında Güçlü Topaklanma", "%99.5 Tozsuz ve Patiye Yapışmaz", "Maksimum Koku Hapsetme Gücü"],
    image: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["En Çok Satan"],
  },
  {
    id: "shop-aktif-karbon-kum",
    name: "Aktif Karbonlu Premium Topaklanan Kedi Kumu",
    brand: "Biokat's",
    category: "eve-petshop",
    subCategory: "Kedi Kumu",
    species: "Kedi",
    price: 320,
    rating: 4.8,
    ratingCount: 94,
    unit: "10 Litre",
    description: "Aktif karbon tanecikleri sayesinde amonyak ve kötü kokuları moleküler düzeyde nötralize eden özel formül.",
    features: ["Aktif Karbon Koku Kilidi", "Ekstra Dayanıklı Topaklar", "Hassas Burunlu Kediler İçin İdeal"],
    image: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "shop-kum-kuregi-tuvalet",
    name: "Ergonomik Elek Kum Küreği & Tuvalet Kabı Seti",
    brand: "Stefanplast",
    category: "eve-petshop",
    subCategory: "Hijyen & Tuvalet",
    species: "Kedi",
    price: 280,
    rating: 4.7,
    ratingCount: 68,
    unit: "Set",
    description: "Yüksek kenarlı kum saçılmasını önleyen kedi tuvalet kabı ve dayanıklı ergonomik elekli kum küreği.",
    features: ["Yüksek kenarlı tasarım (Kum sıçratmaz)", "Kolay temizlenen antibakteriyel plastik", "Hassas elek aralıkları"],
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "shop-tasma-gogus-ergonomik",
    name: "Ayarlanabilir Reflektörlü Göğüs Tasması & Gezdirme",
    brand: "Julius K9 / Truelove",
    category: "eve-petshop",
    subCategory: "Tasma & Gezdirme",
    species: "Köpek",
    price: 340,
    originalPrice: 420,
    rating: 4.9,
    ratingCount: 118,
    unit: "Adet",
    weightOptions: ["S (Small - 4-8 kg)", "M (Medium - 8-18 kg)", "L (Large - 18-35 kg)"],
    description: "Göğsü sıkmayan, ağırlığı gövdeye eşit dağıtan nefes alan kumaşlı ve gece parlayan reflektörlü tasma takımı.",
    features: ["Nefes Alan Yumuşak Dolgu", "Gece Güvenliği İçin 3M Reflektör", "Paslanmaz Çelik D-Halka"],
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Popüler"],
  },
  {
    id: "shop-kedi-tirmalama-tahtasi",
    name: "Doğal Jüt Halatlı Kedi Tırmalama Tahtası & Toplu",
    brand: "PetStyle",
    category: "eve-petshop",
    subCategory: "Tırmalama & Yatak",
    species: "Kedi",
    price: 380,
    originalPrice: 450,
    rating: 4.8,
    ratingCount: 82,
    unit: "50 cm",
    description: "Mobilyalarınızı koruyan, kedinizin tırnak sağlığını ve esneme ihtiyacını karşılayan doğal jüt halatlı tırmalama direği.",
    features: ["%100 Doğal Dayanıklı Jüt", "Sağlam Devrilmez Taban", "Üstte Yaylı Pelüş Oyun Topu"],
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "shop-interaktif-oyuncak-kedi",
    name: "Kedi & Köpek İnteraktif Oyun Seti (Olta + Toplar)",
    brand: "Catit",
    category: "eve-petshop",
    subCategory: "Oyuncaklar",
    species: "Tümü",
    price: 190,
    rating: 4.9,
    ratingCount: 140,
    unit: "Paket",
    description: "Zilli toplar, tüylü teleskopik kedi oltası ve dayanıklı köpek ısırma halatı içeren neşeli aktivite paketi.",
    features: ["Teleskopik Karbon Fiber Olta", "Ses Çıkaran Zilli Toplar", "Diş Temizleyici Pamuk Halat"],
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "shop-elisabeth-yakalik",
    name: "Elisabeth Şeffaf Medikal Koruyucu Korse Yakalık",
    brand: "Buster Medikal",
    category: "eve-petshop",
    subCategory: "Bakım & Medikal",
    species: "Tümü",
    price: 150,
    rating: 4.6,
    ratingCount: 45,
    unit: "Adet",
    weightOptions: ["No:1 (Yavru Kedi)", "No:2 (Yetişkin Kedi)", "No:3 (Küçük Köpek)", "No:4 (Orta Köpek)"],
    description: "Operasyon, dikiş veya dermatolojik tedavi sonrası dostumuzun yarayı yalamasını önleyen yumuşak kenarlı şeffaf yakalık.",
    features: ["Yumuşak Kumaş Kenar Koruma", "Cırt Cırtlı Pratik Ayar", "Şeffaf Görüş Açısı"],
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "shop-tirnak-makasi-seti",
    name: "Emniyet Kilitli Tırnak Makası & Pati Törpü Seti",
    brand: "Doggie Pro",
    category: "eve-petshop",
    subCategory: "Bakım & Medikal",
    species: "Tümü",
    price: 220,
    rating: 4.8,
    ratingCount: 89,
    unit: "Set",
    description: "Paslanmaz çelik keskin bıçaklı, derin kesmeyi önleyen emniyet stoperli tırnak makası ve pati törpüsü.",
    features: ["Emniyet Derinlik Stoperi", "Kaymaz Ergonomik Sap", "Paslanmaz Çelik Bıçaklar"],
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
];

// ==========================================
// 4. EVE TAKVİYE ÜRÜNLERİ (SUPPLEMENT CATALOG)
// ==========================================
export const TAKVIYE_PRODUCTS: ProductItem[] = [
  {
    id: "tak-malt-gimcat",
    name: "GimCat Anti-Hairball Duo-Paste Tüy Yumağı Önleyici Malt",
    brand: "GimCat",
    category: "eve-takviye",
    subCategory: "Malt & Tüy Sağlığı",
    species: "Kedi",
    price: 290,
    originalPrice: 340,
    rating: 5.0,
    ratingCount: 310,
    unit: "100 gr",
    description: "Yalanma sırasında yutulan tüylerin midede yumaklaşmasını önleyen, doğal malt ve peynir aromalı lezzetli macun.",
    features: ["Doğal Aromatik Malt Ekstresi", "Yutulan Tüylerin Dışkıyla Atımı", "Şekersiz ve Koruyucusuz"],
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Veteriner Tavsiyeli", "En Çok Satan"],
  },
  {
    id: "tak-vetexpert-vetomune",
    name: "VetExpert Vetomune Bağışıklık Güçlendirici (Twist-Off)",
    brand: "VetExpert",
    category: "eve-takviye",
    subCategory: "Bağışıklık",
    species: "Tümü",
    price: 640,
    rating: 4.9,
    ratingCount: 165,
    unit: "60 Kapsül",
    description: "Hastalık, aşı dönemi, antibiyotik sonrası ve mevsim geçişlerinde kedi ve köpeklerin humoral ve hücresel bağışıklığını güçlendiren klinik takviye.",
    features: ["Beta-1,3/1,6-Glukan ve HMB Formülü", "Ağza Sıkılabilir Twist-Off Kapsül", "Yüksek Emilim ve Biyoyararlanım"],
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Klinik Seri"],
  },
  {
    id: "tak-vetexpert-arthrovet",
    name: "VetExpert ArthroVet Complex Eklem & Kıkırdak Koruyucu",
    brand: "VetExpert",
    category: "eve-takviye",
    subCategory: "Eklem & Kemik",
    species: "Tümü",
    price: 780,
    originalPrice: 860,
    rating: 4.9,
    ratingCount: 92,
    unit: "60 Tablet",
    description: "Yaşlı veya eklem problemi olan kedi ve köpeklerde Glukozamin, Kondroitin ve Hyaluronik Asit ile eklem sıvısını ve kıkırdağı yenileyen formül.",
    features: ["Glukozamin & Kondroitin & MSM", "Eklem Hareketliliğinde Artış", "Ağrı ve Yangıyı Azaltmaya Yardımcı"],
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "tak-vetqom-qomvit",
    name: "Vetqom QomVit Multivitamin & Biyotin Tüy Bakım Macunu",
    brand: "Vetqom",
    category: "eve-takviye",
    subCategory: "Multivitamin",
    species: "Kedi",
    price: 380,
    rating: 4.8,
    ratingCount: 114,
    unit: "100 gr",
    description: "12 temel vitamin, Biyotin, Çinko ve Taurin içeriği ile tüy dökülmesini belirgin derecede azaltan ve canlılık kazandıran paste.",
    features: ["Tüy Dökülmesini Azaltır", "Taurin ile Kalp ve Göz Desteği", "Kedilerin Bayılarak Yediği Lezzet"],
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "tak-veda-kotbayun",
    name: "Veda KotBayun Bitkisel Sakinleştirici & Anti-Stres Damla",
    brand: "Veda",
    category: "eve-takviye",
    subCategory: "Sakinleştirici",
    species: "Tümü",
    price: 320,
    rating: 4.7,
    ratingCount: 78,
    unit: "50 ml (Damla)",
    description: "Kızgınlık dönemi, yolculuk, gök gürültüsü, taşınma ve klinik ziyareti kaygılarında %100 doğal bitki ekstreleriyle sakinlik sağlayan solüsyon.",
    features: ["%100 Doğal Bitkisel İçerik (Kedi Nanesi, Kediotu)", "Uyuşukluk Yapmayan Sakinlik", "Yan Etkisiz Güvenli Kullanım"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80",
    inStock: true,
    badges: ["Bitkisel"],
  },
  {
    id: "tak-vetux-probiotic",
    name: "Vetux Probiotic & Prebiotic Bağırsak Florası Düzenleyici",
    brand: "Vetux",
    category: "eve-takviye",
    subCategory: "Sindirim & Probiyotik",
    species: "Tümü",
    price: 420,
    rating: 4.9,
    ratingCount: 86,
    unit: "50 gr",
    description: "İshal, kusma veya antibiyotik kürü sonrası bozulmuş bağırsak mikrobiyotasını hızla restore eden canlı probiyotik suşları ve prebiyotik macun.",
    features: ["Enterococcus Faecium Canlı Bakteri", "Hızlı Dışkı Normale Dönüşü", "Sindirim Enzimleri Desteği"],
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
  {
    id: "tak-somon-yagi-omega",
    name: "Wild Salmon Oil Saf Vahşi Somon Yağı (Omega 3 & 6)",
    brand: "Grizzly / Brit Care",
    category: "eve-takviye",
    subCategory: "Tüy & Deri Sağlığı",
    species: "Tümü",
    price: 490,
    originalPrice: 560,
    rating: 4.9,
    ratingCount: 154,
    unit: "250 ml",
    description: "EPA ve DHA yağ asitlerince zengin saf soğuk sıkım somon yağı. Deri kuruluğunu giderir, tüy dökülmesini keser ve parlaklık verir.",
    features: ["Soğuk Sıkım Vahşi Somon Yağı", "Yüksek EPA & DHA Oranı", "Mamaya Eklenen Pratik Pompalı Şişe"],
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80",
    inStock: true,
  },
];

// Combine all products for easy lookup
export const ALL_ECOMMERCE_PRODUCTS: ProductItem[] = [
  ...MAMA_PRODUCTS,
  ...PETSHOP_PRODUCTS,
  ...TAKVIYE_PRODUCTS,
];

// Mock Coupon Codes
export const MOCK_COUPONS: Record<string, { discountPercent?: number; discountFixed?: number; desc: string }> = {
  "VETROTA10": { discountPercent: 10, desc: "%10 Hoş Geldin İndirimi" },
  "PATI20": { discountFixed: 100, desc: "100 ₺ Pati Dostu İndirimi" },
  "EVESAGLIK": { discountPercent: 15, desc: "%15 Evde Sağlık Kampanyası" },
};
