export interface ServiceItemData {
  id: string;
  title: string;
  shortDesc: string;
  price: number;
  duration: string;
  image: string;
  badge?: string;
  category: "evde-saglik" | "klinik" | "asi-parazit" | "tiras-bakim" | "online-danismanlik";
  categoryName: string;
  features: string[];
}

export interface ServiceCategoryTab {
  id: "evde-saglik" | "klinik" | "asi-parazit" | "tiras-bakim" | "online-danismanlik";
  name: string;
  icon: string;
  description: string;
}

export const SERVICE_CATEGORIES: ServiceCategoryTab[] = [
  {
    id: "evde-saglik",
    name: "Evde Sağlık",
    icon: "🏡",
    description: "Kapınızda stressiz fiziki muayene, aşı, tahlil ve medikal bakım.",
  },
  {
    id: "klinik",
    name: "Klinik Muayene",
    icon: "🏥",
    description: "Tam donanımlı klinikte röntgen, ultrason, laboratuvar ve cerrahi.",
  },
  {
    id: "asi-parazit",
    name: "Aşı & Parazit",
    icon: "💉",
    description: "Yıllık koruyucu karma aşılar, kuduz ve iç/dış parazit protokolleri.",
  },
  {
    id: "tiras-bakim",
    name: "Tıraş & Bakım",
    icon: "✂️",
    description: "Anestezisiz profesyonel makas tıraşı, banyo, tırnak ve pati bakımı.",
  },
  {
    id: "online-danismanlik",
    name: "Online Danışmanlık",
    icon: "💻",
    description: "Görüntülü uzman veteriner hekim görüşmesi ve davranış terapisi.",
  },
];

export const ALL_SERVICES: ServiceItemData[] = [
  // 0. GETIRVET 7 TEMEL KATEGORİ ENTEGRASYONU
  {
    id: "evde-saglik",
    title: "1. Evde Sağlık Hizmeti",
    shortDesc: "Aşılama, muayene, parazit uygulama ve daha fazlası kapınızda.",
    price: 850,
    duration: "45 dk",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&auto=format&fit=crop&q=80",
    badge: "Evde",
    category: "evde-saglik",
    categoryName: "Evde Sağlık",
    features: ["Fiziki muayene", "Soğuk zincir aşılar", "Karne onayı"],
  },
  {
    id: "eve-mama",
    title: "2. Eve Mama Hizmeti",
    shortDesc: "Veteriner serisi dahil tüm mama markaları hızlı teslimat ile kapınızda.",
    price: 980,
    duration: "Aynı Gün",
    image: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80",
    category: "evde-saglik",
    categoryName: "Eve Mama",
    features: ["Royal Canin & ProPlan", "İlaçlı Diyet Mamaları", "Kapıda Teslimat"],
  },
  {
    id: "eve-petshop",
    title: "3. Eve Petshop Ürünleri",
    shortDesc: "Oyuncak, kedi kumu, tasma, kıyafet ve hijyen ürünleri.",
    price: 450,
    duration: "Aynı Gün",
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&auto=format&fit=crop&q=80",
    category: "tiras-bakim",
    categoryName: "Petshop Ürünleri",
    features: ["Kedi Kumu & Kürek", "Tasmalar & Oyuncaklar", "Pati Bakım Ürünleri"],
  },
  {
    id: "eve-takviye",
    title: "4. Eve Takviye Ürün Hizmeti",
    shortDesc: "Vitaminler, maltlar ve VetExpert, Vetqom, Veda, Vetux destekleyici ürünler.",
    price: 650,
    duration: "Aynı Gün",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80",
    category: "evde-saglik",
    categoryName: "Gıda Takviyesi",
    features: ["Malt & Vitaminler", "Eklem & Bağışıklık Destekleri", "Orijinal Ürünler"],
  },
  {
    id: "evde-acil",
    title: "5. Evde Acil Durum Hizmeti",
    shortDesc: "7/24 acil mobil müdahale aracı ile hızlı destek.",
    price: 1500,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&auto=format&fit=crop&q=80",
    badge: "Yakında",
    category: "evde-saglik",
    categoryName: "Acil Müdahale",
    features: ["Mobil Müdahale Aracı", "İlk Yardım & Serum", "7/24 Nöbetçi Ekip"],
  },
  {
    id: "online-muayene",
    title: "6. Online Muayene Hizmeti",
    shortDesc: "Uzman veteriner hekimden 30 dk canlı görüntülü muayene ve reçete danışmanlığı.",
    price: 450,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80",
    badge: "Canlı Görüşme",
    category: "online-danismanlik",
    categoryName: "Online Muayene",
    features: ["30 Dk Görüntülü", "E-Reçete Tavsiyesi", "Hızlı Randevu"],
  },
  {
    id: "online-davranis",
    title: "7. Online Veteriner Davranış Danışmanlığı",
    shortDesc: "Davranış problemlerinde profesyonel uzman hekim desteği ve egzersiz planı.",
    price: 700,
    duration: "45 dk",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80",
    badge: "Uzman Terapi",
    category: "online-danismanlik",
    categoryName: "Davranış Danışmanlığı",
    features: ["Davranış Analizi", "Bireysel Egzersiz Planı", "Takip Görüşmesi"],
  },

  // 1. EVDE SAĞLIK HİZMETLERİ
  {
    id: "evde-genel-muayene",
    title: "Evde Genel Muayene",
    shortDesc: "Ev konforunda stressiz fiziki muayene, steteskop dinleme, göz, kulak ve ağız kontrolü.",
    price: 850,
    duration: "45 dk",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&auto=format&fit=crop&q=80",
    badge: "Popüler",
    category: "evde-saglik",
    categoryName: "Evde Sağlık",
    features: ["Fiziki muayene", "Steteskop dinleme", "Karne kontrolü"],
  },
  {
    id: "evde-kan-alma",
    title: "Evde Kan Alma & Laboratuvar",
    shortDesc: "Evde steril kan alımı, soğuk zincirle laboratuvara transfer, hemogram ve biyokimya paneli.",
    price: 950,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80",
    category: "evde-saglik",
    categoryName: "Evde Sağlık",
    features: ["Steril Kan Alımı", "Hemogram & Biyokimya", "Aynı Gün Sonuç"],
  },
  {
    id: "evde-serum-tedavisi",
    title: "Evde Serum & Destek Tedavisi",
    shortDesc: "Dehidrasyon veya enfeksiyon durumlarında damar içi sıvı, elektrolit ve vitamin takviyesi.",
    price: 850,
    duration: "60 dk",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&auto=format&fit=crop&q=80",
    category: "evde-saglik",
    categoryName: "Evde Sağlık",
    features: ["Damar İçi Sıvı Desteği", "Vitamin Kompleksi", "Hekim Gözetimi"],
  },
  {
    id: "evde-mikrocip-kayit",
    title: "Evde Mikroçip & PETVET Kayıt",
    shortDesc: "ISO standartlarında mikroçip uygulaması ve Tarım Bakanlığı PETVET sistemine anlık resmi kayıt.",
    price: 650,
    duration: "25 dk",
    image: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&auto=format&fit=crop&q=80",
    category: "evde-saglik",
    categoryName: "Evde Sağlık",
    features: ["ISO Mikroçip", "PETVET Kaydı", "Resmi Çip Belgesi"],
  },

  // 2. KLİNİK MUAYENE & TEŞHİS
  {
    id: "klinik-kapsamli-muayene",
    title: "Klinikte Kapsamlı Muayene",
    shortDesc: "Donanımlı klinik ortamında başhekim muayenesi, vital bulgular ve klinik check-up.",
    price: 600,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&auto=format&fit=crop&q=80",
    badge: "Klinik",
    category: "klinik",
    categoryName: "Klinik Muayene",
    features: ["Detaylı Check-up", "Vital Bulgular", "Tedavi Planı"],
  },
  {
    id: "klinik-dijital-rontgen",
    title: "Dijital Röntgen & Görüntüleme",
    shortDesc: "Yüksek çözünürlüklü dijital röntgen ile kemik, eklem, göğüs ve batın içi görüntüleme.",
    price: 1100,
    duration: "20 dk",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80",
    category: "klinik",
    categoryName: "Klinik Muayene",
    features: ["HD Dijital Çekim", "Ortopedik İnceleme", "Anında Rapor"],
  },
  {
    id: "klinik-renkli-ultrason",
    title: "Batın Ultrasonografisi",
    shortDesc: "İç organların (karaciğer, böbrek, dalak, mesane vb.) detaylı ultrasonik analizi.",
    price: 1300,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1583912267670-6575ad3624b9?w=800&auto=format&fit=crop&q=80",
    category: "klinik",
    categoryName: "Klinik Muayene",
    features: ["Renkli Doppler", "Organ İncelemesi", "Görüntü Arşivi"],
  },
  {
    id: "klinik-dis-tasi-temizligi",
    title: "Ultrasonik Diş Taşı Temizliği",
    shortDesc: "Tartar ve diş taşlarının kavitron cihazı ile temizliği, diş eti tedavisi ve polisaj bakımı.",
    price: 1800,
    duration: "45 dk",
    image: "https://images.unsplash.com/photo-1606425271394-c3ca9aa1fc06?w=800&auto=format&fit=crop&q=80",
    category: "klinik",
    categoryName: "Klinik Muayene",
    features: ["Kavitron Temizliği", "Diş Eti Bakımı", "Polisaj Cilalama"],
  },

  // 3. AŞI & PARAZİT TAKİBİ
  {
    id: "kedi-karma-asi",
    title: "Kedi Yıllık Karma Aşısı",
    shortDesc: "Panleukopenia, Calicivirus ve Herpesvirüs'e karşı koruyucu soğuk zincir aşısı.",
    price: 750,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&auto=format&fit=crop&q=80",
    badge: "Önemli",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["Soğuk Zincir Aşısı", "3 Virüs Koruması", "Karne İşleme"],
  },
  {
    id: "kopek-karma-asi",
    title: "Köpek Yıllık Karma Aşısı",
    shortDesc: "Distemper, Parvovirus, Adenovirus ve Leptospirosis virüslerine karşı karma aşı.",
    price: 800,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["Geniş Spektrum", "Soğuk Zincir", "Resmi Takvim"],
  },
  {
    id: "kedi-losemi-asi",
    title: "Kedi Lösemi Aşısı (FeLV)",
    shortDesc: "Kedi Lösemi Virüsüne karşı koruma. İlk aşılamalarda hızlı test kiti şarttır.",
    price: 900,
    duration: "35 dk",
    image: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&auto=format&fit=crop&q=80",
    badge: "Test Şartı",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["FeLV Koruması", "İlk Aşıda Hızlı Test", "Karne Onayı"],
  },
  {
    id: "kopek-bronsin-asi",
    title: "Köpek Bronşin (Kennel Cough)",
    shortDesc: "Köpek Barınak Öksürüğü ve solunum yolu enfeksiyonlarına karşı koruyucu aşı.",
    price: 750,
    duration: "25 dk",
    image: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=800&auto=format&fit=crop&q=80",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["Solunum Koruması", "Sosyal Köpekler", "Hekim Uygulaması"],
  },
  {
    id: "kuduz-asi",
    title: "Yasal Yıllık Kuduz Aşısı",
    shortDesc: "Bakanlık onaylı orijinal kuduz aşısı, resmi pasaport ve çip kaydı işletimi.",
    price: 500,
    duration: "25 dk",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&auto=format&fit=crop&q=80",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["Yasal Zorunlu Aşı", "Bakanlık Onayı", "Resmi Onay"],
  },
  {
    id: "kedi-aylik-parazit",
    title: "Kedi Aylık İç/Dış Antiparazit",
    shortDesc: "Pire, kene ve bağırsak parazitlerine karşı 1 aylık orijinal ense damlası ve tablet.",
    price: 650,
    duration: "20 dk",
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800&auto=format&fit=crop&q=80",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["1 Ay Tam Koruma", "Pire & Kene", "Orijinal Damla"],
  },
  {
    id: "kedi-3aylik-parazit",
    title: "Kedi 3 Aylık İç/Dış Antiparazit",
    shortDesc: "3 ay boyunca tam koruma sağlayan, geniş etki spektrumlu premium orijinal paraziter uygulama.",
    price: 1250,
    duration: "20 dk",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&auto=format&fit=crop&q=80",
    badge: "Uzun Koruma",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["3 Ay Kesintisiz Etki", "Geniş Spektrum", "Evde Hızlı Uygulama"],
  },
  {
    id: "kopek-dis-parazit",
    title: "Köpek Dış Parazit Uygulaması",
    shortDesc: "Köpeğinizin kilo aralığına uygun (2.5 - 40 kg) orijinal dış parazit koruması.",
    price: 750,
    duration: "20 dk",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&auto=format&fit=crop&q=80",
    category: "asi-parazit",
    categoryName: "Aşı & Parazit",
    features: ["Kilo Odaklı Dozaj", "Kene & Pire Koruması", "Güvenli Hekim Takibi"],
  },

  // 4. TIRAŞ & MEDİKAL BAKIM
  {
    id: "tiras-makas-kedikopek",
    title: "Anestezisiz Makas Tıraşı",
    shortDesc: "Korkutmadan, sakin yaklaşımla profesyonel makas tıraşı ve model kesim.",
    price: 1100,
    duration: "60 dk",
    image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&auto=format&fit=crop&q=80",
    badge: "Anestezisiz",
    category: "tiras-bakim",
    categoryName: "Tıraş & Bakım",
    features: ["Anestezisiz Kesim", "Model Tıraş", "Stres Yönetimi"],
  },
  {
    id: "medikal-ozon-banyo",
    title: "Medikal & Ozonlu Yıkama Banyosu",
    shortDesc: "Dermatolojik cilt problemleri için özel medikal şampuan ve ozonlu su terapisi.",
    price: 750,
    duration: "40 dk",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&auto=format&fit=crop&q=80",
    category: "tiras-bakim",
    categoryName: "Tıraş & Bakım",
    features: ["Dermatolojik Şampuan", "Ozon Terapi", "Kurutma & Tarama"],
  },
  {
    id: "evde-tirnak-kesimi",
    title: "Tırnak Kesimi & Pati Bakımı",
    shortDesc: "Damara zarar vermeden güvenli tırnak kesimi, pati tüyleri düzeltme ve organik krem.",
    price: 350,
    duration: "20 dk",
    image: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&auto=format&fit=crop&q=80",
    category: "tiras-bakim",
    categoryName: "Tıraş & Bakım",
    features: ["Emniyetli Kesim", "Pati Temizliği", "Organik Nemlendirici"],
  },
  {
    id: "kulak-goz-hijyen-bakimi",
    title: "Kulak & Göz Hijyen Bakımı",
    shortDesc: "Kulak kiri, kulak uyuzu kontrolü ve göz akıntısı steril temizleme kürü.",
    price: 300,
    duration: "15 dk",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80",
    category: "tiras-bakim",
    categoryName: "Tıraş & Bakım",
    features: ["Steril Solüsyon", "Kulak Uyuzu Kontrolü", "Göz Çevresi Bakımı"],
  },

  // 5. ONLINE DANIŞMANLIK & DAVRANIŞ TERAPİSİ
  {
    id: "online-canli-muayene",
    title: "Online Görüntülü Muayene",
    shortDesc: "Uzman veteriner hekim ile 30 dk canlı görüntülü görüşme, tanı ve reçete danışmanlığı.",
    price: 450,
    duration: "30 dk",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80",
    badge: "Canlı Görüşme",
    category: "online-danismanlik",
    categoryName: "Online Danışmanlık",
    features: ["30 Dk Görüntülü", "E-Reçete Tavsiyesi", "Hızlı Randevu"],
  },
  {
    id: "online-davranis-danismanligi",
    title: "Veteriner Davranış Terapisi",
    shortDesc: "Tuvalet eğitimi, kaygı, agresyon, ayrılık anksiyetesi ve havlama problemlerinde uzman hekim desteği.",
    price: 700,
    duration: "45 dk",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&auto=format&fit=crop&q=80",
    badge: "Uzman Destek",
    category: "online-danismanlik",
    categoryName: "Online Danışmanlık",
    features: ["Davranış Analizi", "Bireysel Egzersiz Planı", "Takip Görüşmesi"],
  },
];
